### ISSUE TITLE
Write test cases for transliteration to akhar Cam

### ISSUE THREAD

**Issue by vinhlt88** [Tanginpantangin/web#43]

**Comment by JayamPadra** [comment]
Bugs:

> > Transliteration Inrasara to FontYapata
> > 1- Nao
> > 
> > Transliteration KTT to FontYapata
> > 1- Nao

**Comment by vinhlt88** [comment]
Please create new issues with "bug" label similar to https://github.com/Tanginpantangin/web/issues/54
