### ISSUE TITLE
Fix bug convert from Latin transliteration to Akhar Thrah

### ISSUE THREAD

**Issue by JayamPadra** [Tanginpantangin/web#56]

**Comment by JayamPadra** [comment]
Bug 1: 
(Trans EFEO to Font Yapata): bimong
(Trans Inrasara to Font Yapata): bimong
(Trans KTT to Font Yapata): bimông

**Comment by JayamPadra** [comment]
Bug 2: 
(Trans EFEO to Font Yapata): giém
(Trans Inrasara to Font Yapata): giem
(Trans KTT to Font Yapata): giêm

**Comment by JayamPadra** [comment]
Bug 3: 
(Trans KTT to Font Yapata): ciim

**Comment by JayamPadra** [comment]
Bug 4: idung

**Comment by JayamPadra** [comment]
Bug 5: ["Ak" vowel]
Ex:

> - 1. auix 
> - 2. auen 
> - 3. aiek 
> - 4. li-ar
> - 5. li-aua
> - 6. ma-aom ~ ma-aaom

**Comment by vinhlt88** [comment]
- Fixed: big 1
- Bug 2 -5:  I created these for fixing both of web and windows application
  https://github.com/Tanginpantangin/web/issues/63
  https://github.com/Tanginpantangin/web/issues/64
  https://github.com/Tanginpantangin/web/issues/65
  https://github.com/Tanginpantangin/web/issues/66
